# Generated by Django 6.0.4 on 2026-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lead_doctor',
            field=models.BooleanField(default=False, help_text='Lead Doctor — granted by Super Admin. Can create and manage staff users from the application.'),
        ),
    ]
