# Generated by Django 6.0.4 on 2026-05-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_lead_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('hospital_admin', 'Hospital Administrator'), ('doctor', 'Doctor / Consultant'), ('resident', 'Resident / House Officer'), ('nurse', 'Nurse'), ('chew', 'Community Health Extension Worker (CHEW)'), ('lab_tech', 'Lab Technician / Scientist'), ('radiologist', 'Radiologist / Imaging Tech'), ('pharmacist', 'Pharmacist'), ('billing_officer', 'Billing Officer'), ('receptionist', 'Receptionist'), ('records_officer', 'Records Officer'), ('patient', 'Patient'), ('auditor', 'Auditor')], default='patient', max_length=30),
        ),
    ]
