# Generated by Django 6.0.4 on 2026-09-10 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('antenatal', '0005_ancrecord_babies_count_ancrecord_delivery_mode_and_more'),
        ('patients', '0005_patient_email_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthCertificateSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Birth Certificate Sequence',
            },
        ),
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('certificate_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('child_first_name', models.CharField(max_length=100, verbose_name="Child's first name")),
                ('child_middle_name', models.CharField(blank=True, max_length=100, verbose_name="Child's middle name")),
                ('child_surname', models.CharField(max_length=100, verbose_name="Child's surname")),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Intersex')], max_length=1)),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('time_of_birth', models.TimeField(verbose_name='Time of birth')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Birth weight (kg)')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Length (cm)')),
                ('gestational_age_weeks', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Gestation at birth (weeks)')),
                ('delivery_mode', models.CharField(blank=True, choices=[('svd', 'Spontaneous vaginal delivery (SVD)'), ('assisted', 'Assisted vaginal delivery'), ('cs', 'Caesarean section (C/S)'), ('other', 'Other')], max_length=20, verbose_name='Mode of delivery')),
                ('birth_order', models.PositiveSmallIntegerField(default=1, help_text='1 for the first-born, 2 for the second twin, etc.', verbose_name='Birth order')),
                ('babies_in_delivery', models.PositiveSmallIntegerField(default=1, help_text='1 for a singleton, 2 for twins.', verbose_name='Babies in this delivery')),
                ('father_name', models.CharField(blank=True, max_length=200, verbose_name="Father's full name")),
                ('notes', models.TextField(blank=True, help_text='For the file only — not printed on the certificate.', verbose_name='Internal notes')),
                ('anc_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_records', to='antenatal.ancrecord', verbose_name='ANC record')),
                ('attended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Attending clinician / midwife')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birth_records', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Birth Record',
                'verbose_name_plural': 'Birth Register',
                'ordering': ['-date_of_birth', '-time_of_birth'],
            },
        ),
    ]
