# Generated by Django 6.0.4 on 2026-04-27 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('generic_name', models.CharField(db_index=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup / Suspension'), ('injection', 'Injection'), ('cream', 'Cream / Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('patch', 'Patch'), ('suppository', 'Suppository'), ('other', 'Other')], default='tablet', max_length=20)),
                ('default_route', models.CharField(default='oral', max_length=50)),
                ('category', models.CharField(choices=[('pom', 'Prescription Only (POM)'), ('otc', 'Over the Counter (OTC)'), ('controlled', 'Controlled Drug')], default='pom', max_length=15)),
                ('atc_code', models.CharField(blank=True, max_length=20)),
                ('nafdac_number', models.CharField(blank=True, max_length=50)),
                ('is_formulary', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_frequency', models.CharField(blank=True, max_length=50)),
                ('default_duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['generic_name', 'strength'],
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('contraindicated', 'Contraindicated')], max_length=20)),
                ('description', models.TextField()),
                ('clinical_significance', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='prescriptions.drug')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='prescriptions.drug')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dose', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('sc', 'Subcutaneous'), ('topical', 'Topical'), ('inhaled', 'Inhaled'), ('sublingual', 'Sublingual'), ('rectal', 'Rectal'), ('other', 'Other')], default='oral', max_length=20)),
                ('frequency', models.CharField(choices=[('od', 'Once daily (OD)'), ('bd', 'Twice daily (BD)'), ('tds', 'Three times daily (TDS)'), ('qid', 'Four times daily (QID)'), ('qhs', 'At bedtime'), ('prn', 'As needed (PRN)'), ('stat', 'Immediately (STAT)'), ('weekly', 'Once weekly'), ('other', 'Other')], default='od', max_length=20)),
                ('frequency_other', models.CharField(blank=True, max_length=100)),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('instructions', models.TextField(blank=True)),
                ('is_prn', models.BooleanField(default=False)),
                ('is_stat', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('partial', 'Partially Dispensed'), ('cancelled', 'Cancelled'), ('held', 'On Hold')], default='pending', max_length=20)),
                ('allergy_override_reason', models.TextField(blank=True)),
                ('interaction_override_reason', models.TextField(blank=True)),
                ('refills_allowed', models.PositiveSmallIntegerField(default=0)),
                ('refills_remaining', models.PositiveSmallIntegerField(default=0)),
                ('cosigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosigned_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='prescriptions.drug')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['generic_name'], name='prescriptio_generic_a1e7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['brand_name'], name='prescriptio_brand_n_cee123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='druginteraction',
            unique_together={('drug_a', 'drug_b')},
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='prescriptio_patient_283c70_idx'),
        ),
    ]
