# Generated by Django 6.0.4 on 2026-06-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenatal', '0004_obstetricscan_created_by_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancrecord',
            name='babies_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='e.g. 1 for a singleton, 2 for twins.', null=True, verbose_name='Number of babies'),
        ),
        migrations.AddField(
            model_name='ancrecord',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('svd', 'Spontaneous vaginal delivery (SVD)'), ('assisted', 'Assisted vaginal delivery'), ('cs', 'Caesarean section (C/S)'), ('other', 'Other')], max_length=20, verbose_name='Mode of delivery'),
        ),
        migrations.AddField(
            model_name='ancrecord',
            name='outcome',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered (live birth)'), ('stillbirth', 'Stillbirth'), ('miscarriage', 'Miscarriage / pregnancy loss'), ('transferred', 'Transferred to another facility'), ('other', 'Other')], help_text='How this pregnancy concluded.', max_length=20, verbose_name='Outcome'),
        ),
        migrations.AddField(
            model_name='ancrecord',
            name='outcome_date',
            field=models.DateField(blank=True, null=True, verbose_name='Outcome / delivery date'),
        ),
        migrations.AddField(
            model_name='ancrecord',
            name='outcome_notes',
            field=models.TextField(blank=True, help_text='Delivery summary, baby sex/weight, complications, etc.', verbose_name='Outcome notes'),
        ),
    ]
