# Generated by Django 6.0.4 on 2026-04-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hmo_card',
            field=models.FileField(blank=True, null=True, upload_to='patients/documents/', verbose_name='HMO Card'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hmo_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='HMO Member Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='patients/documents/', verbose_name='ID Document'),
        ),
    ]
