# Generated by Django 6.0.4 on 2026-05-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_populate_unique_patient_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
