# Generated by Django 6.0.4 on 2026-05-06 00:09

from django.db import migrations
from django.db.models import F


def populate_emails(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    db_alias = schema_editor.connection.alias

    # Get all patients that have no email set
    patients_without_email = Patient.objects.using(db_alias).filter(email__isnull=True) | \
                             Patient.objects.using(db_alias).filter(email__exact='')

    for i, patient in enumerate(patients_without_email):
        # Generate a unique placeholder email
        # Using patient.pk ensures uniqueness and is stable across runs
        patient.email = f"patient_{patient.pk}_noemail@example.com"
        patient.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_add_hmo_number_and_documents'),
    ]

    operations = [
        migrations.RunPython(populate_emails, reverse_code=migrations.RunPython.noop),
    ]
